#
# Simple RoundRobin GLB + Loadbalancing for 4 servers
# Hosting 2 domains
#


[cluster]
  binding = "localhost"
  name = "MY_GLB_POOL"
  nodes = ["localhost", "remotehost"]
  secretkey = "yourclusterkey"

[dns]
  binding = "localhost"
  port = 15353
  [dns.domains."domain.nl"]
    ttl = 11
  [dns.domains."domain.nl".soa]

[loadbalancer.settings]
  default_balance_method = "roundrobin"

[loadbalancer.pools.INTERNAL_VIP.listener]
    ip = "127.0.0.1"
    port = 8080
    mode = "http"
  [loadbalancer.pools.INTERNAL_VIP.backends.myapp]
    hostnames = ["www.domain.nl"]
    connectmode="http"
  [loadbalancer.pools.INTERNAL_VIP.backends.myapp.dnsentry]
    domain = "domain.nl"
    hostnames = "www"
  [loadbalancer.pools.INTERNAL_VIP.backends.myapp.healthcheck]
    type = "tcpconnect"
  [[loadbalancer.pools.INTERNAL_VIP.backends.myapp.nodes]]
    hostname = "webserver1"
    ip = "1.2.3.4"
    port = 80
  [[loadbalancer.pools.INTERNAL_VIP.backends.myapp.nodes]]
    hostname = "webserver2"
    ip = "2.3.4.5"
    port = 80

  [loadbalancer.pools.INTERNAL_VIP.backends.myimageapp]
    hostnames = ["image.domain.nl"]
    connectmode="http"
  [loadbalancer.pools.INTERNAL_VIP.backends.myimageapp.dnsentry]
    domain = "domain.nl"
    hostnames = "image"
  [loadbalancer.pools.INTERNAL_VIP.backends.myimageapp.healthcheck]
    type = "tcpconnect"
  [[loadbalancer.pools.INTERNAL_VIP.backends.myimageapp.nodes]]
    hostname = "webserver3"
    ip = "3.4.5.6"
    port = 80
  [[loadbalancer.pools.INTERNAL_VIP.backends.myimageapp.nodes]]
    hostname = "webserver4"
    ip = "4.5.6.7"
    port = 80
