[settings]
  manage_network_interfaces = "yes"
  enable_proxy = "no"
[cluster]
  name = "MY_GLB_POOL"
  [cluster.binding]
  name = "localhost1"
  addr = "127.0.0.1:9000"
  authkey = "test"
  [[cluster.nodes]]
  name = "localhost2"
  addr = "127.0.0.1:10000"
  authkey = "test"

[dns]
  binding = "localhost"
  port = 15353
  [dns.domains."domain.nl"]
    ttl = 11
  [dns.domains."domain.nl".soa]

[loadbalancer.settings]
  default_balance_method = "roundrobin"

[loadbalancer.pools.INTERNAL_VIP.listener]
    ip = "127.0.0.1"
  [loadbalancer.pools.INTERNAL_VIP.backends.myotherapp.dnsentry]
    domain = "domain.nl"
    hostnames = "www"
    ttl = 30
  [loadbalancer.pools.INTERNAL_VIP.backends.myotherapp.healthcheck]
    type = "tcpconnect"
  [[loadbalancer.pools.INTERNAL_VIP.backends.myotherapp.nodes]]
    hostname = "webserver1"
    ip = "1.2.3.4"
    port = 80
  [[loadbalancer.pools.INTERNAL_VIP.backends.myotherapp.nodes]]
    hostname = "webserver2"
    ip = "2.3.4.5"
    port = 80
