# GLB-only example (for use with multiple clouds)
[settings]
  manage_network_interfaces = "no"
  enable_proxy = "no"
[cluster]
  binding = "localhost"
  name = "MY_GLB_POOL"
  nodes = ["localhost", "remotehost"]
  secretkey = "yourclusterkey"

[dns]
  binding = "localhost"
  port = 53
  [dns.domains."domain.nl"]
    ttl = 11
  [dns.domains."domain.nl".soa]

[loadbalancer.settings]
  default_balance_method = "roundrobin"

[loadbalancer.pools.INTERNAL_VIP.listener]
  [loadbalancer.pools.INTERNAL_VIP.backends.myapp.dnsentry]
    domain = "domain.nl"
    hostnames = "www"
    ttl = 30
    ip = "1.2.3.4"
  [loadbalancer.pools.INTERNAL_VIP.backends.myapp.healthcheck]
    type = "tcpconnect"
  [[loadbalancer.pools.INTERNAL_VIP.backends.myapp.nodes]]
    hostname = "dc1_webserver"
    ip = "1.2.3.4"
    port = 80
